### ISSUE TITLE
Factorio hardcrafting mod instalation

### ISSUE THREAD

**Issue by aehaack503** [judos/hardCrafting#1]
when i install the file into the mod folder it says AppData\Roaming\Factorio\mods\source dosent match the expected hardCrafting_0.2.3 (case sensitive!)

**Comment by judos** [comment]
Ah sorry, github somehow didn't show the description when I first looked at it.
This is a minor issue, it's because I zipped my source folder and published it directly. If you unzip the folder then you will not have the mod-name anymore on the file.

**Comment by judos** [comment]
Fixed issue with new v. 0.2.4 - unzipping the mod file won't cause any problems.
