### ISSUE TITLE
Error opening belt sorter GUI

### ISSUE THREAD

**Issue by naryl** [judos/hardCrafting#12]
I'm sorry it happened a few days ago and I don't remember the specifics. I found a quick fix and forgot about it. It seems to have something to with other mods I have, most probably N-Tech Chemistry (since it's the mod which adds ammonia).

When opening the belt sorter GUI the game crashes with an error "unknown style item-ammonia-in-tanker" in libs/itemSelection/control.lua:76. Placing this second condition fixes it:

``` Lua
if filter == "" or string.find(name,filter) then
    if not name:ends("-in-tanker") then
        frame.items.add(checkBoxForItem(name))
        index = index + 1
        if index > mainMaxRows*mainMaxEntries then break end
    end
end
```

string.ends is from here: http://lua-users.org/wiki/StringRecipes

**Comment by judos** [comment]
Hi naryl,
This issue was fixed with hardCrafting_0.3.15.
The new version for factorio 0.13. (hardCrafting_0.4.0) is also out, but doesn't include the belt-sorter anymore. I will split this into a separate mod.
