### ISSUE TITLE
No longer playing

### ISSUE THREAD

**Issue by whitem87** [judos/hardCrafting#14]
Hi 
Since the 13.13 update hard crafting and belt sorter will not allow the game to load. Will you be working to fix the issue 
Thanks

**Comment by judos** [comment]
Thanks for the report. Sorry to hear, I was 2 weeks abroad in vacations. Going to fix it now.

**Comment by whitem87** [comment]
Happy to hear as had hours of fun with this mod. Will you be planning on adding to other ores that are available e.g. Bob ores.

**Comment by judos** [comment]
Yes I definitely planned this. Just until recently I didn't find the time to do it. If you have any propositions I'm open for all ideas ;)

**Comment by judos** [comment]
Fixed with v 0.4.2

@whitem87: Please mark the title of the thread in the mod portal discussion as [fixed]. Thanks!

**Comment by whitem87** [comment]
Well currently playing hard crafting with the full Bob's mods of you could implment them all in the long run it would be a game and half to play.
