### ISSUE TITLE
Error when used with "always-show-recipe-products"

### ISSUE THREAD

**Issue by FKuerten** [judos/hardCrafting#18]
Factorio 0.14.21
hardCrafting_0.5.1 (latest at this time)
always-show-recipe-products 0.1.2 (latest at this time)
If I have both "hardCrafting" and  "always-show-recipe-products" enabled I get the following error on startup:
> Error while running setup for recipe prototype "gravel-pile" (recipe): Unknown item subgroup. No subgroup defined and no main product.
Modifications: hardCrafting › always-show-recipe-products

There may very well be a bug in "always-show-recipe-products", too.
The error seems to be generated from factorio itself. At least I could not find a statement generating this message in either mod.

The "gravel-pile" recipe has an empty string as subgroup. I have never seen a subgroup for recipes in base.
**Changing the empty string to a nil fixes the issue.**

**Comment by judos** [comment]
thanks for the report. Will be fixed with the next release 0.5.2
