### ISSUE TITLE
Recipe reordering

### ISSUE THREAD

**Issue by Dr-Jones** [judos/hardCrafting#23]
In the crafting menu, some of the recipes seem to be in odd places.

In vanilla, stone brick is in the logistics (first) tab. With HardCrafting, there are two recipes for stone brick; one is in the logistics tab, the other is in the intermediate products tab. I think they should both be in the logistics tab. The version that's currently in the intermediate products tab produces gravel as well, but that seems to be more of a byproduct in this case, so I would expect to find this recipe in the logistics tab.

The logistics tab, however, also has a recipe to make 2x gravel from 1x stone. That seems like an obvious candidate for the intermediate products tab, since gravel is the main product of this recipe, and gravel isn't a logistics item but an intermediate item.

**Comment by judos** [comment]
thanks for the report. This fix will be out with 0.15 support in the next version
