### ISSUE TITLE
check hardcrafting port issue

### ISSUE THREAD

**Issue by judos** [judos/hardCrafting#36]
https://mods.factorio.com/mod/hardCrafting2/discussion

**Comment by judos** [comment]
hey @hahoyer,
you mentioned there is another issue? Was it the one with cargo-ships?
I just put the mod in but for me there is no error.

**Comment by hahoyer** [comment]
It is, because I fixed it in version 0.17.2, so it is now also in your version.
So everyting should be fine now

**Comment by judos** [comment]
ok cool, thanks for the fix!
