### ISSUE TITLE
Compiled .zip doesn't work on Mac OSX

### ISSUE THREAD

**Issue by habaneropepper** [judos/hardCrafting#6]
Factorio claims that it can't find info.json after I've placed the hardCrafting_0.3.3.zip into the `~/Library/Application Support/factorio/mods` folder.

When I unzip the file instead, the files come out with directory names and backslashes embedded in the filenames themselves.

For example, info.json is instead a file named `hardCrafting_0.3.3\info.json`. The same is true for all of the sub-directories of the mod. I'm using the default unzip tool that ships with OS X (simply double-clicking the zip file in Finder).

Here's a screenshot that shows the issue:

<img width="1227" alt="screen shot 2016-03-19 at 11 01 42 am" src="https://cloud.githubusercontent.com/assets/17952580/13900388/0a5eb130-edc2-11e5-8096-24551b7e1d4d.png">

**Comment by judos** [comment]
Hi there,
Thanks for the report!
I corrected some mistake in the zipFile implementation for my small build script.
Can you try whether it works fine with the 0.3.4 ?
https://github.com/judos/hardCrafting/releases/download/0.3.4/hardCrafting_0.3.4.zip
Cheers
