### ISSUE TITLE
wrong names, and placement of lua an other files.

### ISSUE THREAD

**Issue by meelock** [judos/hardCrafting#8]
for example hardCrafting_0.3.5\basic-lua-extensions.lua is in the main folder, but is supposed to be: basic-lua-extensions.lua and in the hardCrafting_0.3.5 folder.

**Comment by judos** [comment]
Ups, i fixed this issue with 0.3.4 but I guess I used the old jar again to do the 0.3.5 release. I will do a new release this evening again which is fixed.
Same issue as #6
